### ISSUE TITLE
Update broke almost everything

### ISSUE THREAD

**Issue by Loader23** [klutchell/unbound#21]
Hi,

I have updated to the latest version and it broke nearly everything.^^

- interface no longer runs with port 53
- _unbound user no longer working
- chroot does not work anymore (maybe not needed?)
- auto-trust-anchor not working and the command in the readme is also not working and returns:
 docker run --entrypoint unbound-anchor klutchell/unbound
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /opt/unbound/sbin/unbound-anchor)

While the first 3 Points are easy to fix with port change or deleting the row in config the anchor thing is different.
Maybe I miss something here, any advice appreciated :-)

**Comment by klutchell** [comment]
Hey there, you're correct about the first 3 points, they can be fixed by removing those lines from the config.

The recent images run the daemon as user 'nonroot', so no need to chroot or specify a user anymore. This also means that ports below 1024 will not bind due to lack of permissions. I recommend using docker to map the internal port 5053 to whatever external port you need, often 53.

I just tried running `docker run --rm --entrypoint unbound-anchor klutchell/unbound -v` on my amd64 device and it appears to be successful. Which architecture is your host device running?

**Comment by Loader23** [comment]
Hi, 
thanks for the respond and the explanation. 
Architecture is arm. Its running on a raspberry.

**Comment by klutchell** [comment]
Hmm, I pushed https://github.com/klutchell/unbound/pull/22/commits/5560f8d59f369089d691574b6999f233a31b9f31 to test unbound-anchor on every platform and it seemed to work. I'll have to get out my raspberry pi and try it myself.

In the meantime can you run another `docker pull klutchell/unbound` to ensure you are running the latest image?

**Comment by klutchell** [comment]
I just ran it on a jetson-tx2 and it was successful.

```
$ docker run --rm --entrypoint unbound-anchor klutchell/unbound -v
/var/run/unbound/root.key does not exist
success: the anchor is ok
```

Could you check the output of the image labels?

```
$ docker inspect -f '{{ range $p, $l := .Config.Labels }}{{ $p }}: {{ (println $l) }}{{ end }}' klutchell/unbound
org.opencontainers.image.authors: Kyle Harding <https://klutchell.dev>
org.opencontainers.image.created: 2019-10-29T14:06:45Z
org.opencontainers.image.description: Unbound is a validating, recursive, caching DNS resolver
org.opencontainers.image.documentation: https://klutchell.dev/unbound
org.opencontainers.image.revision: 2bf51af
org.opencontainers.image.source: https://klutchell.dev/unbound
org.opencontainers.image.title: klutchell/unbound
org.opencontainers.image.url: https://klutchell.dev/unbound
org.opencontainers.image.version: 1.9.4

```

**Comment by Loader23** [comment]
Iam using the latest Image. Output of the image label is the same:
`
org.opencontainers.image.authors: Kyle Harding <https://klutchell.dev>
org.opencontainers.image.created: 2019-10-29T14:06:45Z
org.opencontainers.image.description: Unbound is a validating, recursive, caching DNS resolver
org.opencontainers.image.documentation: https://klutchell.dev/unbound
org.opencontainers.image.revision: 2bf51af
org.opencontainers.image.source: https://klutchell.dev/unbound
org.opencontainers.image.title: klutchell/unbound
org.opencontainers.image.url: https://klutchell.dev/unbound
org.opencontainers.image.version: 1.9.4
`

**Comment by klutchell** [comment]
I noticed the instructions on the readme were incorrect for generating a root trust anchor in an existing container. I've updated them just now.

Did you confirm that your **container** is using the latest image as well? You might have to re-create it if you downloaded a more recent image. I just don't see how there can be a gcc dependency when the new images are built in alpine with musl.

**Comment by Loader23** [comment]
Iam using the latest Image. I have also deleted the Image and recreate everything just to make sure. But still, even with the new command the error message is the same.

**Comment by klutchell** [comment]
Could you quickly run `uname -a` so I can test on the exact same system as you?

**Comment by Loader23** [comment]
Linux Pi-Docker 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by klutchell** [comment]
I was able to reproduce the problem on my raspberry pi 3b running rasbian buster. I will investigate and try to push out a fix today.
It seems to only affect arm32v6 and arm32v7 architectures and does not reproduce when emulating platforms via qemu, so it doesn't get flagged during testing.

**Comment by klutchell** [comment]
Can you try pulling today's image and see if unbound-anchor will run?

```
$ docker inspect -f '{{ range $p, $l := .Config.Labels }}{{ $p }}: {{ (println $l) }}{{ end }}' klutchell/unbound
org.opencontainers.image.authors: Kyle Harding <https://klutchell.dev>
org.opencontainers.image.created: 2019-11-01T16:01:20Z
org.opencontainers.image.description: Unbound is a validating, recursive, caching DNS resolver
org.opencontainers.image.documentation: https://klutchell.dev/unbound
org.opencontainers.image.revision: 9d5fd72
org.opencontainers.image.source: https://klutchell.dev/unbound
org.opencontainers.image.title: klutchell/unbound
org.opencontainers.image.url: https://klutchell.dev/unbound
org.opencontainers.image.version: 1.9.4
```

```
$ docker run --rm --entrypoint unbound-anchor klutchell/unbound -v
/var/run/unbound/root.key does not exist
success: the anchor is ok
```

**Comment by Loader23** [comment]
Yes, it is working now. Thanks alot :-)
Do I not need `auto-trust-anchor-file: "var/root.key"` in the unbound.conf anymore? Because having it will result in:
`
[1572646613] unbound[1:0] warning: unbound is already running as pid 1.
[1572646613] unbound[1:0] error: unable to open var/root.key for reading: No such file or directory
[1572646613] unbound[1:0] error: error reading auto-trust-anchor-file: var/root.key
[1572646613] unbound[1:0] error: validator: error in trustanchors config
[1572646613] unbound[1:0] error: validator: could not apply configuration settings.
[1572646613] unbound[1:0] error: module init for module validator failed
[1572646613] unbound[1:0] fatal error: failed to setup modules`

**Comment by klutchell** [comment]
You don't want to provide that value in the config file any more. The default location is `/var/run/unbound/root.key` which is used by unbound for reading and unbound-anchor for writing by default.

**Comment by Loader23** [comment]
Good to know :-)
If you know that a config entry is not needed anymore please provide some kind of changelog for future updates, that would make Updating alot easier :-)
But for now everything is running fine. So thanks alot for all your help.

**Comment by klutchell** [comment]
Agreed, the documentation could use some work. Especially after the recent changes. Thanks for your patience!
